version: '3'

services:

  proxy:
    image: jwilder/nginx-proxy
    networks:
      - my-todo
    ports:
      - "4000:80"
      - "4430:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  mariadb:
    image: bitnami/mariadb:latest
    networks:
      - my-todo
    hostname: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_USER=todoUser
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - ./my-todo-database:/bitnami/mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - my-todo
    environment:
      - VIRTUAL_HOST=my-todo-admin.com
      - PMA_HOST=mariadb
    restart: always

  app:
    build:
      context: ./docker/app-docker
    networks:
      my-todo:
        aliases:
          - my-todo.com
    volumes:
      - .:/var/www/html
    environment:
      - VIRTUAL_HOST=my-todo.com
    restart : always

networks:
  my-todo:
    driver: bridge